version: "2"

services:

  seminar:
    build: .
    #image: sangah/seminar
    ports: 
    - "${HTTP_PORT}:3000"
    - "9615"
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: "unless-stopped"